### ISSUE TITLE
Episode 049: Missing from TGIK playlist and updated Table of Contents

### ISSUE THREAD

**Issue by davecore82** [heptio/tgik#101]
@kris-nova I just noticed episode 049 is missing from the TGI Kubernetes playlist on YouTube.

And also I'd like to suggest this updated Table of Contents for the video description:

- 00:00:00 - Welcome to TGIK!
- 00:07:00 - Week in Review
- 00:29:00 - Introduction - Looking at Flannel
- 00:31:15 - How to turn on --pod-network-cidr
- 00:39:57 - Deploying a pod that doesn't work
- 00:42:47 - Installing Flannel
- 00:51:50 - Looking at various types of Flannel backends
- 00:58:28 - Trick to run CNI Linux-compiled binaries on a Mac
- 01:00:07 - Looking at the Flannel source code
- 01:12:25 - Observing iptables and route tables mutations
- 01:16:48 - Looking at how Calico, Flannel and Canal fit together
- 01:25:05 - Back to iptables and route tables mutations
- 01:30:35 - Wrapping up

Thanks for the great episode!

**Comment by kris-nova** [comment]
Thanks for the note? Would you be interested in opening a PR to the repo? Let me know either way and I can add it too if needed!

**Comment by davecore82** [comment]
I think PR https://github.com/heptio/tgik/pull/104 should be good, let me know if there's anything wrong, I don't git so much.
