### ISSUE TITLE
Episode idea: Pulumi

### ISSUE THREAD

**Issue by sslavic** [heptio/tgik#106]
https://pulumi.io/

**Comment by jbeda** [comment]
Going to do this for TGIK this Friday. Episode 64 - https://twitter.com/jbeda/status/1092963296565587969

**Comment by jbeda** [comment]
HackMD: https://hackmd.io/22GCyjUhTc6FVfTBj6cJ2Q

**Comment by jbeda** [comment]
I think we are good!
