### ISSUE TITLE
Episode idea: Kustomize

### ISSUE THREAD

**Issue by devlounge** [heptio/tgik#111]

**Comment by jbeda** [comment]
Doing Kustomize this week as episode 072.

The process for producing an episode is [here](https://github.com/heptio/tgik/blob/master/documentation/README.md).  All the detail for the steps below is there.

Monday or Tuesday:
* [ ] Pick a topic and create/use an issue in the repo
* [ ] If applicable coordinate with an upstream project if they're interested in attending the show
* [ ] Create the graphic
* [ ] Schedule on Youtube
* [ ] Add scheduled episode to TGIK playlist on YT
* [ ] Create short link in rebrandly
* [ ] Tweet about it from your personal account
  * [ ] Post tweets on internal #tgik slack channel and cc @castrojo and @boschem
  * [ ] Get confirmation from @boschem that he's seen the tweet and is scheduling it

Before episode:
* [ ] Create HackMD page for live notes.  Start with README template in this repo
* [ ] Paste HackMD URL on internal #tgik channel and cc @castrojo or other assistant
  * [ ] Assistant adds ~5-10 news items from around the web as possible "News of the Week"
* [ ] Get everything tested well before episode so you can debug
* [ ] Use internal slack channel to ensure that AV setup is good


After show (ideally right away but can wait until Monday):
* Create/submit PR for this repo
  * [ ] Episode directory and README from hackmd
  * [ ] Any other files from the episode that might be useful
  * [ ] Update playlist.md with episode
  * Feel free to self merge
* [ ] Edit YT description to point to episode directory here
* [ ] OBS/OS Upgrade if applicable (Never on the day of a show)

**Comment by jbeda** [comment]
https://j.hept.io/tgik072

**Comment by pwittrock** [comment]
This looks great, can't wait to see it.

FYI, the most recent Kustomize documentation is in the new [kubectl docs](https://kubectl.docs.kubernetes.io/pages/app_management/apply.html)

**Comment by jbeda** [comment]
Jetstack article on cert-manager+kustomize: https://blog.jetstack.io/blog/kustomize-cert-manager/

**Comment by jbeda** [comment]
hackmd: https://hackmd.io/dn0KfrC3R3awmHpEgFMQSw?edit
