### ISSUE TITLE
Episode Idea: Hashicorp Vault on Kubernetes

### ISSUE THREAD

**Issue by petermbenjamin** [heptio/tgik#130]

**Comment by dlaidlaw** [comment]
This one was done on Nov. 16, 2018

**Comment by coolpalani** [comment]
@petermbenjamin 
You can find clips from here: https://www.youtube.com/watch?v=7aR6k9xBN94

**Comment by petermbenjamin** [comment]
Awesome. Thanks.
Closed by https://github.com/heptio/tgik/commit/7a036fb1531cf524887a1787402b5e4e774e25c3
