### ISSUE TITLE
Episode Idea: Kubernetes Admission Control and OPA

### ISSUE THREAD

**Issue by joysarkarhub** [heptio/tgik#135]

**Comment by jbeda** [comment]
Specifically look at https://github.com/open-policy-agent/gatekeeper.  I'd like to do this one soon.

**Comment by jbeda** [comment]
I'm going to do this this week: https://j.hept.io/tgik071

Monday or Tuesday:
* [ ] Pick a topic and create/use an issue in the repo
* [ ] If applicable coordinate with an upstream project if they're interested in attending the show
* [ ] Create the graphic
* [ ] Schedule on Youtube
* [ ] Add scheduled episode to TGIK playlist on YT
* [ ] Create short link in rebrandly
* [ ] Tweet about it from your personal account
  * [ ] Post tweets on internal #tgik slack channel and cc @castrojo and @boschem
  * [ ] Get confirmation from @boschem that he's seen the tweet and is scheduling it

Before episode:
* [ ] Create HackMD page for live notes.  Start with README template in this repo
* [ ] Paste HackMD URL on internal #tgik channel and cc @castrojo or other assistant
  * [ ] Assistant adds ~5-10 news items from around the web as possible "News of the Week"
* [ ] Get everything tested well before episode so you can debug
* [ ] Use internal slack channel to ensure that AV setup is good


After show (ideally right away but can wait until Monday):
* Create/submit PR for this repo
  * [ ] Episode directory and README from hackmd
  * [ ] Any other files from the episode that might be useful
  * [ ] Update playlist.md with episode
  * Feel free to self merge
* [ ] Edit YT description to point to episode directory here
* [ ] OBS/OS Upgrade if applicable (Never on the day of a show)

Links for the episode:
* https://www.cncf.io/blog/2019/04/02/toc-votes-to-move-opa-into-cncf-incubator/
* https://www.openpolicyagent.org/
* https://www.openpolicyagent.org/docs/
* https://github.com/open-policy-agent/gatekeeper
* https://github.com/open-policy-agent/opa

**Comment by tsandall** [comment]
I recommend getting started with the Kubernetes admission control tutorial on openpolicyagent.org: https://www.openpolicyagent.org/docs/kubernetes-admission-control.html. The tutorial takes you through deploying OPA from scratch, enabling the webhook, deploying a policy, exercising the policy, updating the policy, etc. This is how most people try out OPA for admission control for the first time.

In addition to the tutorial, we recently put together a primer/guide on writing admission control policies: https://github.com/open-policy-agent/opa/blob/master/docs/content/docs/guides-kubernetes-admission-control.md. The guide goes into detail on how admission control policies are structured and evaluated.

A couple other pointers that might be helpful:

* [Language Reference](https://www.openpolicyagent.org/docs/language-reference.html). This page lists all the various built-in functions for things like string manipulation, regexp, etc.

* [Rego Cheatsheet](https://github.com/open-policy-agent/opa/blob/master/docs/content/docs/rego-cheatsheet.md). Compact reference doc for common expressions in OPA (e.g., looking up values, iterating over arrays, etc.)

Lastly, when it comes to writing Rego, you could check out the [VS Code extension](https://github.com/tsandall/vscode-opa) and [play.openpolicyagent.org](https://play.openpolicyagent.org/). Both provide ability to evaluate the policies interactively.

As far as Gatekeeper goes, we're in the middle of restructuring the controller quite a bit and we don't have the same kind of docs yet. The policy authoring experience is more or less the same in Gatekeeper (i.e., users write `deny` rules that enforce constraints on `input` which gets bound to the AdmissionReview object.) Once Gatekeeper is ready, there will be additional features like a constraint library and audit capability that might be good fodder for a future episode :D

**Comment by jbeda** [comment]
A more in depth article that @mauilion pointed me at: https://itnext.io/optimizing-open-policy-agent-based-kubernetes-authorization-via-go-execution-tracer-7b439bb5dc5b?gi=414d224ebdc7

**Comment by jbeda** [comment]
HackMD: https://hackmd.io/e8NXFMdAQ06SeOuXkAZYmA?view
