### ISSUE TITLE
Episode idea: kube2iam/kiam

### ISSUE THREAD

**Issue by Comradin** [heptio/tgik#175]
kube2iam provides/controles access to AWS resources via IAM roles.

Project repository:
https://github.com/jtblin/kube2iam

**Comment by jbeda** [comment]
Going to do this along with https://github.com/uswitch/kiam.

**Comment by jbeda** [comment]
See also https://www.bluematador.com/blog/iam-access-in-kubernetes-kube2iam-vs-kiam

**Comment by jbeda** [comment]
The process for producing an episode is [here](https://github.com/heptio/tgik/blob/master/documentation/README.md).  All the detail for the steps below is there.

Monday or Tuesday:
* [ ] Pick a topic and create/use an issue in the repo
* [ ] If applicable coordinate with an upstream project if they're interested in attending the show
* [ ] Create the graphic
* [ ] Schedule on Youtube
* [ ] Add scheduled episode to TGIK playlist on YT
* [ ] Create short link in rebrandly
* [ ] Tweet about it from your personal account
  * [ ] Post tweets on internal #tgik slack channel and cc @castrojo and @boschem
  * [ ] Get confirmation from @boschem that he's seen the tweet and is scheduling it

Before episode:
* [ ] Create HackMD page for live notes.  Start with README template in this repo
* [ ] Paste HackMD URL on internal #tgik channel and cc @castrojo or other assistant
  * [ ] Assistant adds ~5-10 news items from around the web as possible "News of the Week"
* [ ] Get everything tested well before episode so you can debug
* [ ] Use internal slack channel to ensure that AV setup is good


After show (ideally right away but can wait until Monday):
* Create/submit PR for this repo
  * [ ] Episode directory and README from hackmd
  * [ ] Any other files from the episode that might be useful
  * [ ] Update playlist.md with episode
  * Feel free to self merge
* [ ] Edit YT description to point to episode directory here
* [ ] OBS/OS Upgrade if applicable (Never on the day of a show)

**Comment by jbeda** [comment]
Also: https://github.com/mikkeloscar/kube-aws-iam-controller

**Comment by jbeda** [comment]
For GCP: https://github.com/imduffy15/k8s-gke-service-account-assigner

**Comment by randomvariable** [comment]
Some other bits that may be useful:

* [AWS's future plan to use service account token volume projection](https://github.com/aws/containers-roadmap/issues/23)
* [Comparison of various AWS credential providers circa June 2016](https://docs.google.com/document/d/1rn-v2TNH9k4Oz-VuaueP77ANE5p-5Ua89obK2JaArfg/edit)
* [Old KEP on starting a canonical metadata proxy implementation in kubernetes-sigs, superseded by the OIDC plan above](https://github.com/pingles/community/blob/c29578eef06ae7c3651dda5a7f34b92d7f403303/keps/sig-aws/0014-iam-credentials-provider.md)

**Comment by jbeda** [comment]
HackMD: https://hackmd.io/RcYsuHhyQT2vsuG4-Sh29A?edit
