### ISSUE TITLE
Episode Idea: Pod Security Policies

### ISSUE THREAD

**Issue by Matty9191** [heptio/tgik#195]

**Comment by joshrosso** [comment]
Monday or Tuesday:
* [x] Pick a topic and create/use an issue in the repo
* [x] If applicable coordinate with an upstream project if they're interested in attending the show
* [ ] Create the graphic
* [ ] Schedule on Youtube
* [ ] Add scheduled episode to TGIK playlist on YT
* [ ] Create short link in rebrandly
* [ ] Tweet about it from your personal account
  * [ ] Post tweets on internal #tgik slack channel and cc @castrojo and @boschem
  * [ ] Get confirmation from @boschem that he's seen the tweet and is scheduling it

Before episode:
* [x] Create HackMD page for live notes.  Start with README template in this repo
* [ ] Paste HackMD URL on internal #tgik channel and cc @castrojo or other assistant
  * [ ] Assistant adds ~5-10 news items from around the web as possible "News of the Week"
* [ ] Get everything tested well before episode so you can debug
* [ ] Use internal slack channel to ensure that AV setup is good


After show (ideally right away but can wait until Monday):
* Create/submit PR for this repo
  * [ ] Episode directory and README from hackmd
  * [ ] Any other files from the episode that might be useful
  * [ ] Update playlist.md with episode
  * Feel free to self merge
* [ ] Edit YT description to point to episode directory here
* [ ] OBS/OS Upgrade if applicable (Never on the day of a show)

**Comment by marcindulak** [comment]
Streamed as TGI Kubernetes 078, but the "After show" directory is missing
