### ISSUE TITLE
Episode Idea: Network Policy

### ISSUE THREAD

**Issue by guibirow** [heptio/tgik#202]
After watching the amazing episode hosted by @joshrosso 
 about pod security policies, I wondered if you guys could make a follow up about Network Policies.

**Comment by joshrosso** [comment]
@guibirow, fantastic idea.

I'll run this by @mauilion and @jbeda as a potential future episode.

In the mean time, I have covered this concept with a video and blog post here: https://octetz.com/posts/k8s-network-policy-apis

Sorry for the self-plug :)

Regardless, this would make a great TGIK episode!

**Comment by guibirow** [comment]
Amazing stuff Josh
Just watched it, if you do TGIK on this subject for sure I will watch it again
Just the video seems to be cut before the finish, but I could follow the rest from the tutorial.

In the TGIK, can you guys also get into more details about the internals of CNI plugins like:
- Why it need specific CNI pluggins and what happens behind the scenes
- Good practices
- Your experiences using these policies on default CNI used by Managed Kubernetes offerings like GKE, AKS, EKS, (VMWARE)KS

Thanks Again!

**Comment by joshrosso** [comment]
Great! Thanks for the feedback and hopefully we'll get this in a TGIK in the future :+1:

**Comment by joshrosso** [comment]
Monday or Tuesday:
* [x] Pick a topic and create/use an issue in the repo
* [x] If applicable coordinate with an upstream project if they're interested in attending the show
* [x] Create the graphic
* [x] Schedule on Youtube
* [x] Add scheduled episode to TGIK playlist on YT
* [x] Create short link in rebrandly
* [x] Tweet about it from your personal account
  * [x] Post tweets on internal #tgik slack channel and cc @castrojo and @boschem
  * [x] Get confirmation from @boschem that he's seen the tweet and is scheduling it

Before episode:
* [x] Create HackMD page for live notes.  Start with README template in this repo
* [x] Paste HackMD URL on internal #tgik channel and cc @castrojo or other assistant
  * [x] Assistant adds ~5-10 news items from around the web as possible "News of the Week"
* [x] Get everything tested well before episode so you can debug
* [x] Use internal slack channel to ensure that AV setup is good


After show (ideally right away but can wait until Monday):
* Create/submit PR for this repo
  * [x] Episode directory and README from hackmd
  * [x] Any other files from the episode that might be useful
  * [x] Update playlist.md with episode
  * Feel free to self merge
* [x] Edit YT description to point to episode directory here
* [x] OBS/OS Upgrade if applicable (Never on the day of a show)
