### ISSUE TITLE
TGIK Suggestion for Kubebuilder

### ISSUE THREAD

**Issue by droot** [heptio/tgik#6]
[Kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) is a framework for building Kubernetes APIs using custom resource definitions (CRDs). It provides powerful libraries and tools to simplify building and publishing Kubernetes APIs from scratch.

It is a sub project under APIMachinery SIG. More details can be found [here](https://github.com/kubernetes-sigs/kubebuilder).

**Comment by jbeda** [comment]
I'm going to do this for TGIK 083.  Haven't done real coding in a while and want to do kubebuilder to build a minecraft controller. 

The process for producing an episode is [here](https://github.com/heptio/tgik/blob/master/documentation/README.md).  All the detail for the steps below is there.

Monday or Tuesday:
* [ ] Pick a topic and create/use an issue in the repo
* [ ] If applicable coordinate with an upstream project if they're interested in attending the show
* [ ] Create the graphic
* [ ] Schedule on Youtube
* [ ] Add scheduled episode to TGIK playlist on YT
* [ ] Create short link in rebrandly
* [ ] Tweet about it from your personal account
  * [ ] Post tweets on internal #tgik slack channel and cc @castrojo and boschem
  * [ ] Get confirmation from boschem that she's seen the tweet and is scheduling it

Before episode:
* [ ] Create HackMD page for live notes.  Start with README template in this repo
* [ ] Paste HackMD URL on internal #tgik channel and cc @castrojo or other assistant
  * [ ] Assistant adds ~5-10 news items from around the web as possible "News of the Week"
* [ ] Get everything tested well before episode so you can debug
* [ ] Use internal slack channel to ensure that AV setup is good


After show (ideally right away but can wait until Monday):
* Create/submit PR for this repo
  * [ ] Episode directory and README from hackmd
  * [ ] Any other files from the episode that might be useful
  * [ ] Update playlist.md with episode
  * Feel free to self merge
* [ ] Edit YT description to point to episode directory here
* [ ] OBS/OS Upgrade if applicable (Never on the day of a show)

**Comment by jbeda** [comment]
https://tgik.io/083

Going to start with https://book.kubebuilder.io/quick-start.html and https://github.com/itzg/dockerfiles.
