### ISSUE TITLE
Suggestion - Use HackMD-it Browser Extension for Editing Show Notes

### ISSUE THREAD

**Issue by chadswen** [heptio/tgik#82]
@jbeda @kris-nova @castrojo Glad to see all the HackMD love in the latest episodes! I've recently gone HackMD crazy (I use it for everything) and thought I'd suggest the HackMD-it browser extension that adds an `Edit on HackMD` button to Markdown files on GitHub (and GitLab).

[HackMD-it for Chrome](https://chrome.google.com/webstore/detail/hackmd-it/cnephjboabhkldgfpdokefccdofncdjh?hl=en)
[HackMD-it for Firefox](https://addons.mozilla.org/zh-TW/firefox/addon/hackmd-it/)
[HackMD-it issue tracker](https://github.com/hackmdio/hackmd-it-issues)

Bonus link: [CodiMD Helm Chart](https://github.com/helm/charts/tree/master/stable/hackmd) - free software version of HackMD, which has been great for my on-prem notes!

Not sure if this issue was a good way to leave TGIK "suggestion box" feedback, but feel free to close.

Enjoy!

**Comment by castrojo** [comment]
Chad, this is incredible, thanks so much for this tip. I would _love_ to get more k8s people into hackmd (in fact, I was introduced to it at kubecon!) 

Feel free to ping me on slack (I'm `@jorge` on there) or via my contact info on github, I'd love to talk about how the community can use this tool. Thanks for the tip!
